apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: product-service
build:
  artifacts:
    - image: product-service
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8/*.yaml
