apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: order-service
build:
  artifacts:
    - image: order-service
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8/*.yaml
